project:
  name: "bookstore"
  host: "https://dbc-134e30eb-a774.cloud.databricks.com/"
  token: "dapi269ac03c813a54aa5c3ceb72e67a0c3b"
  root: "bookstoredatabricks"

buckets:
  - type: "rawdata"
    name: "bookstorerawdata"
    iam_role: "arn:aws:iam::302263052839:role/databricks-s3-ingest-3fcda-db_s3_iam"
  - type: "databricks:"
    name: "bookstoredatabricks"
    iam_role: "arn:aws:iam::302263052839:role/databricks-s3-ingest-f00cb-db_s3_iam"

dwh_structure:
  catalogs:
    - name: "ct_bookstore"
      databases: 
        - name: "db_bronze"
        - name: "db_silver"
        - name: "db_gold"
        
